//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditorias.ProxyServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServicio.IServicioWCF")]
    public interface IServicioWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/DoWork", ReplyAction="http://tempuri.org/IServicioWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/DoWork", ReplyAction="http://tempuri.org/IServicioWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/GuardarCarro", ReplyAction="http://tempuri.org/IServicioWCF/GuardarCarroResponse")]
        string GuardarCarro(prueba.Carro carro, prueba.Fabricante fabricante, string parametro2, int parametro3, System.DateTime parametro4, double parametro5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWCF/GuardarCarro", ReplyAction="http://tempuri.org/IServicioWCF/GuardarCarroResponse")]
        System.Threading.Tasks.Task<string> GuardarCarroAsync(prueba.Carro carro, prueba.Fabricante fabricante, string parametro2, int parametro3, System.DateTime parametro4, double parametro5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioWCFChannel : Auditorias.ProxyServicio.IServicioWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWCFClient : System.ServiceModel.ClientBase<Auditorias.ProxyServicio.IServicioWCF>, Auditorias.ProxyServicio.IServicioWCF {
        
        public ServicioWCFClient() {
        }
        
        public ServicioWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GuardarCarro(prueba.Carro carro, prueba.Fabricante fabricante, string parametro2, int parametro3, System.DateTime parametro4, double parametro5) {
            return base.Channel.GuardarCarro(carro, fabricante, parametro2, parametro3, parametro4, parametro5);
        }
        
        public System.Threading.Tasks.Task<string> GuardarCarroAsync(prueba.Carro carro, prueba.Fabricante fabricante, string parametro2, int parametro3, System.DateTime parametro4, double parametro5) {
            return base.Channel.GuardarCarroAsync(carro, fabricante, parametro2, parametro3, parametro4, parametro5);
        }
    }
}
